#!/bin/bash
set -e

if [  "${UPDATE_BLACKLIST_URL}" != "" ]; then
	sudo wget ${UPDATE_BLACKLIST_URL} \
 		&& tar -xzf shallalist.tar.gz -C /var/lib/squidguard/db \
 		&& rm shallalist.tar.gz \
 		&& chown proxy:proxy /var/lib/squidguard/db -R
fi

if [ ! -f /etc/squidguard/squidGuard.conf ]; then
	if [  "${SQUID_CONFIG_SOURCE}" != "" ]; then
		echo "no configuration found -> use ${SQUID_CONFIG_SOURCE}/squidGuard.conf"		
		# test mac os
		sudo usermod -u 1000 proxy
		ln -s ${SQUID_CONFIG_SOURCE}/squidGuard.conf /etc/squidguard/squidGuard.conf
	elif [  "${UPDATE_BLACKLIST_URL}" != "" ]; then
	    echo "no configuration found -> use /sample-config-blacklist"
		ln -s /sample-config-blacklist/squidGuard.conf /etc/squidguard/squidGuard.conf
	else
	    echo "no configuration found -> use /sample-config-simple"
		ln -s /sample-config-simple/squidGuard.conf /etc/squidguard/squidGuard.conf
	fi
	sudo chown -R proxy:proxy /var/lib/squidguard/db
fi
sudo -u proxy squidGuard -C all

echo "running startSquidGuard with WPAD_IP=${WPAD_IP} WPAD_NOPROXY_NET=${WPAD_NOPROXY_NET} WPAD_NOPROXY_MASK=${WPAD_NOPROXY_MASK}"

if [  "${WPAD_IP}" != "" ]; then
	sed 's/{{WPAD_IP}}/'"${WPAD_IP}"'/' -i /var/www/html/wpad.dat
	sed 's/{{WPAD_NOPROXY_NET}}/'"${WPAD_NOPROXY_NET}"'/' -i /var/www/html/wpad.dat
	sed 's/{{WPAD_NOPROXY_MASK}}/'"${WPAD_NOPROXY_MASK}"'/' -i /var/www/html/wpad.dat
fi

# start apache to serve wpad.dat file and or block.html
sudo /etc/init.d/apache2 restart

# run original squid start script
exec /sbin/entrypoint.sh
