#!/bin/bash
set -e

echo "running startSquidGuard with WPAT_IP=${WPAT_IP} WPAT_NOPROXY_NET=${WPAT_NOPROXY_NET} WPAT_NOPROXY_MASK=${WPAT_NOPROXY_MASK}"

if [  "${WPAT_IP}" != "" ]; then
	sed 's/{{WPAT_IP}}/'"${WPAT_IP}"'/' -i /var/www/html/wpat.dat
	sed 's/{{WPAT_NOPROXY_NET}}/'"${WPAT_NOPROXY_NET}"'/' -i /var/www/html/wpat.dat
	sed 's/{{WPAT_NOPROXY_MASK}}/'"${WPAT_NOPROXY_MASK}"'/' -i /var/www/html/wpat.dat
fi

# start apache to serve wpat.dat file and or block.html
sudo /etc/init.d/apache2 restart

# run original squid start script
exec /sbin/entrypoint.sh
