#!/bin/bash
set -e

if [  "${UPDATE_BLACKLIST_URL}" != "" ]; then
	sudo wget ${UPDATE_BLACKLIST_URL} \
 		&& tar -xzf shallalist.tar.gz -C /var/lib/squidguard/db \
 		&& rm shallalist.tar.gz \
 		&& chown proxy:proxy /var/lib/squidguard/db -R
fi

if [ ! -f /etc/squidguard/squidGuard.conf ]; then
	if [  "${SQUID_CONFIG_SOURCE}" != "" ]; then
		echo "no configuration found -> use ${SQUID_CONFIG_SOURCE}/squidGuard.conf"
		ln -s ${SQUID_CONFIG_SOURCE}/squidGuard.conf /etc/squidguard/squidGuard.conf
		sudo chown -R proxy:proxy ${SQUID_CONFIG_SOURCE}
	elif [  "${UPDATE_BLACKLIST_URL}" != "" ]; then
	    echo "no configuration found -> use /sample-config-blacklist"
		ln -s /sample-config-blacklist/squidGuard.conf /etc/squidguard/squidGuard.conf
	else
	    echo "no configuration found -> use /sample-config-simple"
		ln -s /sample-config-simple/squidGuard.conf /etc/squidguard/squidGuard.conf
	fi
	sudo chown -R proxy:proxy /var/lib/squidguard/db
	sudo -u proxy squidGuard -C all 
fi

echo "running startSquidGuard with WPAT_IP=${WPAT_IP} WPAT_NOPROXY_NET=${WPAT_NOPROXY_NET} WPAT_NOPROXY_MASK=${WPAT_NOPROXY_MASK}"

if [  "${WPAT_IP}" != "" ]; then
	sed 's/{{WPAT_IP}}/'"${WPAT_IP}"'/' -i /var/www/html/wpat.dat
	sed 's/{{WPAT_NOPROXY_NET}}/'"${WPAT_NOPROXY_NET}"'/' -i /var/www/html/wpat.dat
	sed 's/{{WPAT_NOPROXY_MASK}}/'"${WPAT_NOPROXY_MASK}"'/' -i /var/www/html/wpat.dat
fi

# start apache to serve wpat.dat file and or block.html
sudo /etc/init.d/apache2 restart

# run original squid start script
exec /sbin/entrypoint.sh
